name: Install Dependencies

inputs:
    which-dependencies:
        description: "Which dependencies to install"
        required: true
        default: "codespell"

runs:
    using: "composite"
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          if: ${{ inputs.which-dependencies == 'codespell'}}
          with:
              python-version: "3.9"
        - run: pip install codespell
          shell: bash
