name: Test ZIG files

on:
    pull_request:
        branches:
            - main
        paths:
            - '**.zig'
            - '**/**.zig'
            - '.github/workflows/test-zig-files.yml'

jobs:
    Simple-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - uses: actions/checkout@v4
            - uses: mlugg/setup-zig@v1
            - run: |
                  zig test beginner_basics.zig
                  zig test testing_stuff.zig
                  zig test intermediate_basics.zig
                  zig test advanced_basics.zig
                  echo 'Avi Fenesh' | zig test standard_library.zig
              working-directory: ziging
              shell: bash

    HW-test:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - uses: actions/checkout@v4
            - uses: mlugg/setup-zig@v1
            - run: |
                  echo 'testing P0-tests.zig'
                  zig test src/P0-tests.zig
                  echo 'testing utils.zig'
                  zig test src/utils.zig
              working-directory: Project0-word
              shell: bash

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: mlugg/setup-zig@v1
            - run: zig fmt --check .
