name: Test spelling files

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Dependencies
              uses: ./.github/workflows/Install-dependencies
              with:
                  which-dependencies: codespell

            - name: Run codespell
              working-directory: ./
              shell: bash
              run: codespell -q 3 -I ./ignore_files/.codespellignore .
