name: Test ZIG files

on:
    pull_request:
        branches:
            - main
        paths:
            - "**.zig"
            - "**/**.zig"
            - ".github/workflows/test-zig-files.yml"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Dependencies
              uses: ./.github/workflows/Install-dependencies

            - name: Run tests on ZIG file change
              working-directory: ziging
              shell: bash
              run: |
                  zig test basics.zig
                  zig test testing_stuff.zig
